### ISSUE TITLE
Failed to activate the variational-java package

### ISSUE THREAD

**Issue by itAaronhua** [milesvdw/VJava-Atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Unknown Windows version
**Thrown From**: [variational-java](https://github.com/milesvdw/VJava-Atom) package 0.7.5

### Stack Trace

Failed to activate the variational-java package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:145974)
    at /packages/VJava-Atom-0.7.5/lib/variational-java.js:3:24)
    at /packages/VJava-Atom-0.7.5/lib/variational-java.js:733:27)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:626990)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3039740)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027874)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1192024)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349490)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:348333)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:656662)
    at EventEmitter.t (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:664046)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:58.4.0 application:open-file (input.hidden-input)
     -2:50.9.0 editor:newline (input.hidden-input)
  9x -2:48.3.0 core:backspace (input.hidden-input)
  2x -2:35.3.0 core:move-left (input.hidden-input)
  2x -2:33.4.0 core:move-right (input.hidden-input)
     -2:32.9.0 editor:newline (input.hidden-input)
  8x -2:28.9.0 core:backspace (input.hidden-input)
     -2:26.8.0 core:save (input.hidden-input)
  2x -2:24.3.0 editor:newline (input.hidden-input)
  2x -2:23.9.0 core:move-up (input.hidden-input)
     -2:15.8.0 editor:newline (input.hidden-input)
 20x -2:11.9.0 core:backspace (input.hidden-input)
     -2:03.3.0 core:save (input.hidden-input)
     -0:26.3.0 editor:toggle-line-comments (input.hidden-input)
  5x -0:23.2.0 core:backspace (input.hidden-input)
     -0:11.1.0 variational-java:toggle (input.hidden-input)
```

### Non-Core Packages

```
simplified-chinese-menu 5.3.5 
variational-java 0.7.5 
```

**Comment by milesvdw** [comment]
This looks like maybe you need to npm install? This package uses jquery for DOM manipulation so if that's not present it will fail. Unrelated: are you using this repository? I thought it was dead!
